### ISSUE TITLE
2023.10.30 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#10]
- [ ] 진행 중인 팀 프로젝트 개발하기
- [x] 자동차 경주 미션 커밋 올리기
- [ ] 자동차 경주 미션 테스트 코드 작성하기
- [ ] 시간 남으면 클래스 컴포넌트 형태의 리액트 익히기
[ReactJS로 영화 웹서비스 만들기](https://nomadcoders.co/react-for-beginners/lobby?utm_source=free_course&utm_campaign=react-for-beginners&utm_medium=site)

**Comment by Largopie** [comment]
오늘은...! 생각보다 내가 해야할 일을 많이 끝내지 못했다. 그 이유라 함은 내가 작성한 코드가 객체지향적이지 못하다는 부분에서 다시 코드를 작성하느라 쓰지 못했다..!! 현재는 자동차 경주 미션을 다시 짜보는데 집중하는 중이다. 아직은 다른 부분보다 미션이 끝나기 전에 자동차 경주 미션을 완료하는데 집중해야겠다는 생각이 들었다. 내일은 하루종일 자동차 경주 미션에 매달려보는걸로...
