### ISSUE TITLE
2024.01.31 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#101]
- [x] 코딩테스트 1문제 풀기
- [x] React 클래스 컴포넌트 강의 수강
- [x] 모의면접 스터디 질문 1개 답변하기

**Comment by Largopie** [comment]
클래스 컴포넌트의 라이프사이클을 드디어 조~금(?)은 알 수 있었다.(그 전에 이미 한 번 학습한 경험이 있음). 해당 클래스 컴포넌트 강의로 직접 state를 관리하며 영화 웹서비스를 제작해보고 조금 더 깊게 알면 좋을 것 같다.
