### ISSUE TITLE
2024.02.01 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#102]
- [x] 코딩테스트 1문제 이상 풀기
- [ ] 리액트 클래스 컴포넌트 강의 수강
- [x] 모의 면접 스터디 질문 답변 1개 작성하기
- [x] 모던 자바스크립트 딥다이브 17장 읽기

**Comment by Largopie** [comment]
.
