### ISSUE TITLE
2023.11.01 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#12]
- [x] 알고리즘 문제 해설 기능 구현(졸업 작품)
- [x] 코드 리팩토링 기능 구현(졸업 작품)
- [x] 주석 생성 기능 구현(졸업 작품)
- [x] 프로젝트를 진행하며 리팩토링 고민하기
- [x] 프로젝트 회의 진행
- [x] 코딩 테스트 풀기

**Comment by Largopie** [comment]
오늘은 할 수 있는 기능 빠르게 구현하고, 리팩토링을 차라리 하자! 라는 마음가짐으로 기능 구현을 우선적으로 생각하고 구현했다. 다음주 11월 7일에 1차 리허설 발표가 있는데 그 전에 디자인적인 부분이 깔끔하게 해결 된다면 조금 더 퀄리티 있는 프로젝트가 되지 않을까 싶은 마음에 조금 심혈을 기울여서 만들어야 할 필요가 있을 것 같다. 

그리고 오늘은 크루스칼 알고리즘에 대해 공부했다. 다음에는 문제를 보고 '어, 이거 크루스칼 알고리즘으로 풀면 빨리 풀겠다!'라는 생각이 될 수 있게끔 내가 공부한 내용을 정리했다.

그리고 시간이 조금 남아서 취업 관련된 정보들을 조금 수집하고 회사를 조금 지원했다. 좋은 기회가 닿길..
