### ISSUE TITLE
2023.11.03 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#14]
- [x] 우아한테크코스 문제 파악 및 기능 구현 문서 작성
- [x] 졸업작품 프로젝트 배포
- [x] EC2, Nginx로 React 배포에 관한 블로그 글 쓰기
- [x] 졸업작품 html title, favicon 수정

**Comment by Largopie** [comment]
휴 오늘은 일정을 잘 마무리 한 것 같다. EC2와 NGINX를 이용해 사이트 배포도 정상적으로 완료했고, 해당 내용에 관한 블로그도 포스트 했다..! 
항상 생각하지만 내가 정확한 내용을 알고 있어야만 블로그를 작성할 수 있는 것 같다는 생각이 든다. 기자의 마음이 이해가 된달까.. 나 말고도 다른 사람들이 참고해서 문제를 해결해야 한다고 생각하니 잘못된 정보를 기입하면 안되겠다 라는 생각이 먼저 들어 블로그를 적는데 머뭇하는 부분도 없잖아 있다고 생각한다.

그래도 나는 내가 다시 찾아볼 수 있도록, 그리고 글을 쓰는데 부담이 없도록 작성하는데에 우선시하여 글을 작성하고 있다.
나중에는 더 발전된 사람이 되었을 때 공식 문서를 보고 빠르게 내 생각을 정리해 나타낼 수 있는 사람이 되었으면 좋겠다.

내일은 우아한테크코스에 올인해서 열심히 또 달려보자! 오늘 고생했다! 👍
