### ISSUE TITLE
2023.11.04 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#15]
- [x] 우테코 3주차 문제 "몰입"하기
- [x] 우테코 2주차 미션 미러 푸쉬하기
- [x] 모의면접 스터디 - 모의 면접 진행

**Comment by Largopie** [comment]
어제 너무 정신없는 터라 이제서야 회고를 남기게 되었다..! 어제는 정신 없이 하루가 지나간 것 같다.. 🥹 모의 면접 스크립트 준비, 우테코 문제 재정의, 해결, 코드 리뷰 등.. 이것 저것 하다보니 어느새 하루가 끝나 있었는데, 간단히 코드 리뷰에 대한 생각을 적어보고자 한다.

 코드 리뷰 하는데 확실히 시간은 많이 걸리나 내가 코드를 작성하는 '당위성'에 대해서 다시 고민해볼 수 있는 것 같다. '왜 이렇게 코드를 작성했을까?'에 대해서 한 번 더 고민하고 의견을 남길 수 있는 코드 리뷰가 정말 좋은 것 같다. 덕분에 남의 코드를 읽고 이해할 수 있는 능력도 길러지고, 내가 생각했던 부분과 일치한지도 검증이 가능하고 말이다.. ㅎㅎ 1주차때 코드리뷰 요청 게시글을 올렸지만 리뷰가 하나도 없어 너무 슬퍼서 이번에 어그로성으로 글을 올린 덕분에 실력있으신 분들께 피드백도 받고 관점도 넓어지고, 다른 사람은 코드를 어떻게 작성했을까를 살펴볼 수 있어서 좋았던 것 같다..! 아래는 어그로성 글 ㅋㅋ

<img width="846" alt="image" src="https://github.com/Largopie/TIL/assets/106071687/60b683a9-e04e-45e1-8269-fcb4b84f992e">

아무튼 우테코를 하면서 정말 많은 걸 배워가는 것 같다 ㅎㅎ 오늘도 미션 해결에 집중하며 열심히 가보자!
