### ISSUE TITLE
2023.11.06 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#17]
- [x] 우아한테크코스 3주차 테스트케이스 통과하기(ApplicationTest)
- [x] 성공하면 조금의 리팩토링 하기!
- [x] AWS EC2 + NGINX 배포 경험 공유하기!
- [x] 원티드 클린코드 강의 수강 ( 20시 ~ 23시)

**Comment by Largopie** [comment]
휴.. 아침 8시부터 오후 4시까지 눈이 뚫어지도록 에러가 무엇인지 찾고 있었다.. 결국 해내고야 말았다..!
나는 정말 요구 사항을 꼼꼼히 읽어야겠다는 생각이 들었다. 예외 처리가 발생 시 에러를 `throw`한 후 **[재입력]** 받았어야 했다. 나는 저번 주차는 당연히 에러를 `throw` 후 게임을 종료했기 때문에 이번 주차도 그럴 것이라는 안일함을 가지고 있었다고 생각한다.

이를 통해서 조금 더 요구사항을 꼼꼼히 읽어보고 하나하나 세세하게 정리한 후 기능 요구 사항을 작성했다고 깨달음을 얻을 수 있는 경험이였다.

또한 오늘은 원티드 프론트엔드 챌린지로 클린 코드에 대한 고민을 해볼 수 있었다. 어떤 코드가 과연 클린한 코드인가..?에 대해 생각해볼 수 있는 시간이였다..! 강의 자료를 찾다가 아직 안올라와서 자세한 내용에 대해선 아직 정의가 되지 않았지만..!

몽키 패치? get 과 generate의 차이, 개행을 언제 해주는 것이 좋을까 등 코드의 가독성을 높이기 위해서 고민해보기로 했다.

그리고 프로젝트 팀원에게 AWS + EC2를 배포한 경험을 공유했다..! 어떤식으로 배포를 진행했는지..! 그리고 FileZilla에 접근권한을 어떻게 얻어서 파일이 옮겨지는지..! 등등..! 나도 자세한건 정확하게 모르니 이제부터라도 차근차근 배워나가야겠다
