### ISSUE TITLE
2023.11.08 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#18]
PS. 어제는 정신없이 리팩토링을 하다가 시간이 다가버려서 TODO 리스트를 쓰는것 조차 잊고 코딩했다...! 그리고 학교 수업도 풀수업이라 쓸 겨를이 없었던 것 같다..!
어제는 이력서 첨삭, 우테코 코드리팩토링을 중점적으로 진행했다.
- [x] 우테코 3주차 코드 리팩토링 및 테스트케이스 작성
- [x] 최대한 오늘 내로 끝내고 제출하기
- [x] 시간이 남는다면 코딩테스트 문제풀기

**Comment by Largopie** [comment]
휴.. 오늘은 다행히도 모든 할 일을 끝냈다.(아마도?) 계속 코드를 살펴보며 리팩토링할 수 있는 부분에 대해서 최대한 리팩토링을 진행해봤지만 잘 됐는지는 잘 모르겠다 .. 😂 아마 아쉬운 부분도 분명 있을텐데 어찌 됐던 좋은 '경험'을 하고 있다고 생각하고 최대한 끌어내서 결과를 도출했다고 생각한다..!

1주차, 2주차, 3주차 프리코스에 대한 회고는 작성하지 않았지만 우테코 프리코스를 진행하며,, 라는 주제로 우테코 프리코스의 느낀점에 대한 블로그 글을 작성해볼까 한다..! 그 전에 미리 피드백도 받고 어떤 내용을 적으면 좋을지에 대해서 고민해보는 것이 좋을 것 같다.

내일 3시부터 문제가 열리니 문제가 열리기 전까지는 강의를 듣거나, 코테를 풀거나, 졸업작품 프로젝트 마무리를 하는 방향으로 진행해봐야겠다. 그럼 오늘도 끝! 🏁
