### ISSUE TITLE
2023.11.09 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#19]
- [x] 3시 이후, 우테코 4주차 문제 파악하기!! <매우 중요>
- [x] 졸업작품 프로젝트 진행 사항 체크하고 이슈 해결하기
- [x] 코딩테스트 한 문제 풀기
- [ ] 시간이 빈다면.. 트위터 클론코딩 or ReactJS로 영화 웹사이트 만들기(클래스 컴포넌트 버전) 듣기
- [ ] 구름톤 8기 지원서 작성

**Comment by Largopie** [comment]
이슈는 2가지 해결했지만.. 코드 하이라이터를 적용하는데 굉장히 어려움을 겪고 있다...
prismjs를 사용하자니 코드 라인넘버가 출력이 안되고, highlight.js를 이용하자니 렌더링 시 이용이 안되다보니 이 부분을 어떻게 해결하면 좋을지 지속적으로 고민해보고 적용해봐야겠다.. 심지어 참고할 수 있는 블로그도 많지 않은 것 같아서 열심히 공식문서 보면서 삽질중이다 ㅎㅎ.. 해결되면 뿌듯할듯 싶다! 블로그 글이 되겠군!!

우테코도 지문이 이상했는지 내가 질문을 남기자 문법이 변경됐다.. 😂(어제 두시간 삽질한건 안비밀) 원하는 답을 얻어서 속이 시원하긴하다!
