### ISSUE TITLE
2023.11.12 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#21]
- [x] 구름톤 지원서 작성
- [x] 코딩테스트 1문제 풀기
- [x] 면접 스터디 면접 준비
- [x] 코드 하이라이팅 다듬기(모든 대화에 적용이 되고 있음, 일부분에만 적용할 수 있도록 고민해보자)

**Comment by Largopie** [comment]
어제는 조금 간단하게 많은 일은 하지는 않고, 코드 하이라이팅 기능 구현, 구름톤 지원서 작성, 코딩 테스트를 풀었다. 우테코가 거의 끝나가다 보니 조금의 여유는 생긴 것 같아 마음이 한결 가벼워진 것 같다. 내일은 우테코 리팩토링, 코테 문제 풀기, 강의 수강 등 여러 일이 남았는데 차근차근 또 나아가보려 한다. 꾸준함이 계속 지속될 수 있도록 체력 관리를 잘 해야겠다!
