### ISSUE TITLE
2023.11.13 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#22]
- [ ] 코딩테스트 1문제 풀기
- [ ] 우테코 리팩토링
- [x] 프로젝트 해결 사항 해결하기
- [x] 원티드 11월 챌린지 수강

**Comment by Largopie** [comment]
어우.. 어제는 일을 해서그런지 집중을 잘 못했다.. 그래서 프로젝트 해결 사항을 해결하는데 중점을 두고 열심히 하다보니 하루가 지나가고 2시가 훌쩍 넘어서 끝나자마자 자버렸다.. 거기다 10시 30분에 진행한 퀴즈도 있어서 더더욱 시간이 부족했던 것 같다..!! 내일 졸업작품 발표가 마무리 되면 조금 더 집중해서 해봐야겠다.. 오늘도 열심히..!
