### ISSUE TITLE
2023.11.14 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#23]
- [x] 우테코 제출 및 리팩토링
- [x] 구름톤 지원서 작성
- [x] 졸업작품 프로젝트 발표 준비 및 발표

**Comment by Largopie** [comment]
우테코 최종 제출을 완료했다..! 지원서도 어찌저찌 여기저기 조언을 구해가며 완성은 했다(제출은 내일함). 그리고 졸업작품 발표도 잘 마무리 되었다. 오늘 하루에 이것저것 마무리 된 일이 많은데, 내일은 우테코 제출 기간이 마감되지 않았으므로 최종적으로 코드에 대한 점검을 진행해야겠다. 그리고 앞으로는 현재 백엔드 친구와 같이 기획하는 프로젝트 하나를 진행하고, 면접 스터디, 자바스크립트 스터티에 다시 집중을 해야할 것 같다..! 그리고 조금 더 여유를 가지고 천천히 나아갈 생각이다. 오늘 하루 끗
