### ISSUE TITLE
2023.11.15 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#24]
- [ ] 면접 스터디 준비
(2주차-[스코프 ~ strict mode], 3주차-[이벤트루프~에러객체])
- [ ] 면접 스터디 [모의 면접]
- [x] 우테코 4주차 리팩토링
- [x] 구름톤 지원

**Comment by Largopie** [comment]
지난 주 동안 우테코 4주차, 학교 졸업작품에 신경쓰느라 면접 스터디 준비를 소홀하게 했다. 그런데 마침 2명이 개인사정으로 빠지게 되는 바람에 더 공부를 하고. 모의 면접에 응할 수 있는 시간이 생겼다. 아무튼 다음 면접 스터디 진행 시간까지 열심히 학습해서 대답을 최대한 잘 할 수 있도록 꾸준히 학습해야겠다는 생각이 들었다. (그래서 SQL이랑 코테 한문제 풀었다.) 내일도 열심히!
