### ISSUE TITLE
2023.11.16 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#25]
- [ ] SQL, 코딩테스트 문제 1개 씩 풀기
- [ ] 면접 스터디 준비
- [ ] 사이드 프로젝트 기획(동준식)

**Comment by Largopie** [comment]
오늘은 동준식 프로젝트를 어떤 방향으로 진행할지 논의하고, 해당 공부를 진행했다. 동준식은 동양미래대학교에서 준비한 식사로, 학식 알림 서비스이다. 평소에 학식을 먹으면서 오늘의 메뉴가 궁금했는데 찾아보기에는 귀찮음이 있었다. 그래서 학식을 알림으로 알려주는 서비스가 있으면 좋겠다고 생각해서 기획하게 됐다. 얼른 만들어서 배포해봐야지! 오늘 끝! 

내일부터 3일간은 아르바이트를 진행해서 바쁠 것 같다 ㅠㅠ 그래서 최소한 SQL, 코딩테스트 1문제를 푸는 것을 목표로 잡고 진행해봐야겠다!
