### ISSUE TITLE
2023.11.23 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#32]
- [x] 오전에 면접 스터디 질문지 작성
- [x] 리액트 네이티브 배포 방법 학습
- [ ] SQL, 코딩테스트 1문제씩 풀기
- [ ] 동준식 기획 회의

**Comment by Largopie** [comment]
리액트 네이티브를 엑스포를 이용해서 만들면 정말 편하다. 하지만, 엑스포가 아닌 cli로 작업을 하면 정말 어렵다고 느껴졌다.. 그래서 하루종일 세팅을 하고 있었는데 진지하게 react native를 배워볼까 고민이다. 하루 마무리..!
