### ISSUE TITLE
2023.11.24 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#33]
- [x] SQL, 코딩테스트 1문제 풀기
- [x] 2시 면접
- [x] 오전에 파이썬 프로젝트 진행한거 보고 가기
- [x] 리액트 네이티브 고민 더 해보기..
- [x] 프로그래머스 지원서 초안 작성
- [x] 면접 스터디 6주차 문제 올리기
