### ISSUE TITLE
2023.11.26 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#35]
- [x] OCU 취업성공전략 레포트 작성하기
- [x] OCU 생활과화학 레포트 작성하기
- [x] SQL, 코딩테스트 1문제씩 풀기
- [x] 자기소개서 수정하기
- [x] 원티드 12월 프론트엔드 챌린지 사전 과제 수행
- [x] 리액트 네이티브 프로젝트 세팅

**Comment by Largopie** [comment]
약간의 리액트 네이티브 세팅을 완료했다. 하지만 지금 만드는 프로젝트를 expo로도 개발할 수 있을지에 대한 고민도 해봐야겠다. 초기 세팅이 많이 복잡해서 expo로 배포하고자 한다. 이따 프로젝트 세팅 진행해 봐야지
