### ISSUE TITLE
2023.11.27 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#36]
- [x] SQL, 코딩테스트 1개씩 풀기
- [x] OCU 생활과 화학 리포트 제출
- [x] PWA 개념 숙지 및 프로젝트 구축해보기
- [x] 트위터 클론코딩 강의 수강

**Comment by Largopie** [comment]
기존에 expo로 앱을 구축해보려 했지만 PWA라는 방법이 있어 웹상에서 모바일처럼 구현하는 방법을 찾아 적용해보려 한다. 간단한 개념만 숙지했기 때문에 나중에 제대로 알아보고 적용해봐야겠다.

ps. vercel로 일반적인 배포는 성공했음!
