### ISSUE TITLE
2023.12.01 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#37]
- [ ] 취업성공전략 기말고사 응시
- [x] [공개SW페스티벌] 스프린트 참여
- [ ] SQL, 코딩테스트 1문제 풀기
- [ ] 트위터 & 파이어베이스 챌린지 1일차 참여

**Comment by Largopie** [comment]
공개SW페스티벌에 참여했다. 해서 기여할 수 있는 시간을 갖게 되었다. 앞으로도 번역을 기여했던 내용을 바탕으로 다른 오픈소스에도 기여할 수 있으면 좋겠다는 생각이 들었다.
대신.. 어제 너무 정신이 없는 나머지.. 취성전 기말고사를 응시하지 못했다.. 내 실책이다.. 기억을 하고있었는데 새까맣게 잊어버렸네... 아쉽다..
