### ISSUE TITLE
2023.11.28 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#38]
- [x] 면접 스터디 질문 대답 작성 (최소 10개 이상은 작성할 것)
- [x] SQL, 코딩테스트 1문제씩 풀기
- [x] 포트폴리오 파일 개별적으로 만들기
- [ ] 시간이 남는다면 트위터 클론코딩 강의 듣기

**Comment by Largopie** [comment]
오늘은 면접 스터디 질문에 대한 대답을 찾아 작성하고, 포트폴리오 파일을 분리하여 개별적으로 만들었다.
생각보다 포트폴리오 줄이 길어져서 조금 줄일까 고민을 해보긴 해야겠다. 그래도 오늘 해야할 일을 빡빡히 모두 수행한 것 같아서 기분이 약간 좋다. 조금씩 다듬어지는 느낌이야!
