### ISSUE TITLE
2023.11.29 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#39]
- [x] SQL, 코딩테스트 문제 1개씩 풀기
- [x] twitter & firebase 강의 수강
- [ ] 프로젝트 기획회의
- [x] 면접스터디 질문 대답 완성

**Comment by Largopie** [comment]
무난하게 할 거 다 한 하루였다. 특별한건 없었고, 트위터 & 파이어베이스 강의를 들으면서 확실히 백엔드 없이도 이렇게 로그인을 구현할 수 있구나 싶은게 참 좋았다.
