### ISSUE TITLE
2023.11.30 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#40]
- [ ] SQL, 코딩테스트 1문제 풀기
- [x] 트위터 & 파이어베이스 강의 수강
- [x] JSON에 대해서 설명할 수 있을 정도로 알아보기

**Comment by Largopie** [comment]
useEffect() cleanup, teardown 학습하기

**Comment by Largopie** [comment]
트위터 파이어베이스에 관한 강의를 거의 다 수강했다. 이외 특별한 점은 없었던 것 같다.
