### ISSUE TITLE
2023.12.02 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#42]
- [x] 트위터 & 파이어베이스 코드챌린지 과제 수행
- [x] SQL, 코딩테스트 1문제 풀기
- [x] 동준식 헤더 개발

**Comment by Largopie** [comment]
트위터 페이지를 피그마를 이용해서 완전히 똑같이 디자인 해봤다. 모든 부분을 비율로 잘라서 만들어봤는데 매우 재밌었다!!
무에서 유를 창조하는 일은 어렵지만 클론은 재밌는 느낌이군.. UX/UI도 공부해야하는데... 일단 화이팅이다
