### ISSUE TITLE
2023.12.03 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#43]
- [x] SQL, 코딩테스트 1문제 풀기
- [ ] 트위터 & 파이어베이스 과제 수행
- [x] draw.io로 시스템 구성도 제작해보기
