### ISSUE TITLE
2023.12.04 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#44]
- [x] SQL, 코딩테스트 1문제 풀기
- [x] firebase & twitter 과제 복습 및 수행
- [x] 전에 듣고 있던 firebase & twitter 강의 마무리

**Comment by Largopie** [comment]
이번에 복습을 수행하면서 트위터를 비슷하게 만들어보자 라는 생각으로 기본 색상을 선택한 후 트위터 사이트와 일치하게 만들고 있다..! 오늘 할게 많으니 열심히 해나가자!
