### ISSUE TITLE
2023.12.05 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#45]
- [x] 모의 면접 스크립트 준비(최소 10개 이상)
- [x] SQL, 코딩테스트 1문제 이상풀기
- [ ] 트위터 클론코딩 로그인 기능 구현

**Comment by Largopie** [comment]
시간이 부족해서 로그인 기능 구현은 아쉽지만 내일로 미뤘다. 오늘은 오전 + 오후 풀수업에 야간근로까지 하다보니 시간이 부족한게 느껴진다 ㅠ 오늘 더 열심히 해야지
