### ISSUE TITLE
2023.12.07 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#47]
- [x] 지원서, 포트폴리오 완성 후 지원
- [x] SQL, 코딩테스트 1문제 풀기
- [x] switter 게시판 기능 구현(할 수 있는 만큼)
- [ ] 면접 스터디 공부

**Comment by Largopie** [comment]
오늘 면접 스터디 공부는 못했지만 게시판 기능 구현은 완료했다. 글을 지우는 기능, 수정기능을 추가하는것이 내일 목표다!! 그리고 면접 스터디 공부도 해야하는데!!
