### ISSUE TITLE
2023.12.08 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#48]
- [x] SQL, 코딩테스트 각 한 문제씩 풀기
- [ ] 졸업논문 해당 파트 부분 작성
- [x] twitter & firebase 게시판 수정, 삭제 기능 완료

**Comment by Largopie** [comment]
어제는 게시판 수정, 삭제 기능을 구현했다. 파이어베이스를 사용하니까 백엔드 연동 없이 편리하게 사용할 수 있는 점이 좋았다. 이제 마지막으로 프로필을 수정하는 기능을 구현하면 끝이 난다. 마지막도 열심히..!
