### ISSUE TITLE
2023.12.19 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#59]
- [x] 코딩테스트 1문제 풀기
- [x] 동준식 기획 회의
- [x] 모의 면접 스터디 준비
- [ ] 트위터 파이어베이스 프로필 기능 만들기

**Comment by Largopie** [comment]
20일 오늘을 기점으로 대학교에서 진행하던 근로아르바이트도 끝이났다. 일단 쉼 없이 달려왔던 2~3달간의 여정에서 학교도 끝이 났고, 잠깐의 휴식 기간을 거쳐가려 한다. 그래도 최대한 하루에 하나 이상씩의 유의미한 커밋은 유지해보려 노력할 예정이다.

여러 회사에 지원서도 많이 넣어보았지만, 아직 취업을 해야하는 시기라는게 실감이 나지 않는다. 곧 회사원이라니.. 하하 아직 해야할 공부는 많은데 취업은 해야하고 여러 모든 결정을 하는데 심혈을 기울여야하는 시기인 것 같다. 그래도 또 연말까지는 쉬엄쉬엄 가자~!
