### ISSUE TITLE
2023.12.21 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#61]
- [x] 코딩테스트 1문제 풀기
- [x] 트위터 & 파이어베이스 프로필 완성
- [x] 트위터 & 파이어베이스 배포
- [x] 면접 스터디 준비

**Comment by Largopie** [comment]
드디어 트위터 & 파이어베이스 배포를 했다! 저기에서 정말 많은 걸 배운 것 같다. 또 추가적으로 리팩토링 해보면서 페이지를 개선해 나가야겠다.
