### ISSUE TITLE
2023.12.22 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#62]
- [x] 코딩테스트 1문제 풀기
- [x] 면접 스터디 준비
- [x] 인터렉티브 개발 실무 강의 수강

**Comment by Largopie** [comment]
여행을 다녀와서 이제야 회고를 작성해서 기억이 뚜렷하지는 않지만 한가지는 기억이 난다. 인터렉티브 개발 실무 강의!! 내가 직접 인터렉티브 웹을 응용해보고 있다. 그래서 웹상에서 룰렛이 어떻게 돌아가는지 원리가 파악됐다! 신기하다!
