### ISSUE TITLE
2023.12.24 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#64]
- [x] 코딩테스트 1문제 풀기
- [x] switter README.md 작성
- [x] 인터렉티브 웹 강의 수강

**Comment by Largopie** [comment]
오늘도 깔끔하게 놀러 다녀와서도 공부했다! 라는 느낌 ㅎㅎ
