### ISSUE TITLE
2023.10.27 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#7]
## 오늘 할 일
- [x] 우아한테크코스 2주차 문제 해결하기
- [x] React LifeCycle 정리하기
- [x] 프리온보딩 FE 챌린지 11월 사전과제 해결하기
