### ISSUE TITLE
2024.01.02 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#72]
- [x] 코딩테스트 1문제 풀기
- [x] 모던 자바스크립트 딥다이브 9장 학습하기
- [ ] 인터렉티브 웹 강의 수강하기

**Comment by Largopie** [comment]
점점 어려운 문제들이 나오다 보니 코딩테스트에 투자하는 시간이 많아진다 ㅠㅠ 그래도 차근차근 개념을 익히면서 풀어나가봐야겠다.
