### ISSUE TITLE
2024.01.03 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#73]
- [x] 코딩테스트 1문제 풀기
- [ ] 자바스크립트 딥다이브 10장 보기
- [x] 인터렉티브 웹 강의 수강

**Comment by Largopie** [comment]
이제 이사할 방을 보러 다니고 있다. 그래서 오전에 공부 후 오후에는 방을 보러 다니고 있는데 방 값이 장난 아니다.. 친구와 자취를 하기 위해 투룸을 알아보고 있는데 보증금이 거의 기본적으로 2000만원 선이니.. 꼭 좋은 방 구할 수 있기를..
