### ISSUE TITLE
2024.01.04 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#74]
- [x] 코딩테스트 1문제 풀기
- [x] 모던 자바스크립트 딥다이브 10장 읽기
- [ ] 모던자바스크립트 튜토리얼 엄격모드, 함수 표현식 읽고 정리
- [x] 인터렉티브 웹 강의 수강

**Comment by Largopie** [comment]
엄격모드, 함수 표현식은 내일 읽기로했다. 휴 방구하느라 정신이 없다!! 조금씩 천천히 나아가자~
