### ISSUE TITLE
2024.01.05 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#75]
- [x] 코딩테스트 1문제 풀기
- [x]  모던자바스크립트 튜토리얼 엄격모드, 함수 표현식 읽고 머리속으로 정리
- [x] 모던 자바스크립트 딥다이브 스터디 (8시)

**Comment by Largopie** [comment]
어제 꽤 생산적인 대화를 많이 했다. 9장에 나오는 타입 변환과 단축평가, 10장에 나오는 객체 리터럴에서 책에 나오는 내용과 관련된 다양한 이야기를 했다. 나는 구체적으로 우테코에서 사용했던 airbnb style guide를 예시로 들며 ES6문법을 조금 더 잘 활용할 수 있도록 설명했다. 잘 설명했는지는 모르겠지만 서로서로 이렇게 개념에 대해서 설명하면서 관점 차이를 이야기 해보는 것이 매우 좋은 것 같다.
