### ISSUE TITLE
2023.10.28 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#8]
- [x] React LifeCycle 복습
- [ ] 우아한테크코스 1주차 공통 피드백 수용해서 자동차 경주 리팩토링 하기
- [x] TEOConf 참여하기(사진찍고 후기 작성)
- [ ] 면접 스터디 모의 면접 준비

**Comment by Largopie** [comment]
## 회고
오늘 TEOConf에 참여하다보니 시간이 많이 늦어져 나머지 준비는 하지 못했다. 하지만 TEOConf에서 많은걸 경험했고, 또 다양한 사람들을 만날 수 있었던 좋은 시간이였던 것 같다. 오늘 못 끝낸 일은 내일 마저 마무리 하는 것으로 하고, 어제보다 나은 사람이 되기 위해 더 노력해야겠다고 느꼈다.

시간이 나면 TEOConf 후기도 블로그에 써야겠다.
