### ISSUE TITLE
2024.01.10 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#80]
- [x] 코딩테스트 1문제 풀기
- [x] 자바스크립트 딥 다이브 11장 읽고 정리
- [x] 인터렉티브 웹 강의 수강

**Comment by Largopie** [comment]
어제는 윕 WIP 문래창작촌으로 공부를 하러 가보았다. 확실히 집중은 잘되고 공부 효율은 좋았으나, 매장 안의 한기가 온몸을 감싸서 너무 추운 상태로 공부를 했다. 하지만 빡 집중해서 할 수 있는 일을 다 끝내서 다행이라고 생각한다.
