### ISSUE TITLE
2024.01.11 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#81]
- [x] 인터렉티브 웹 강의 수강
- [x] 코딩테스트 1문제 풀기
- [x] 모던 자바스크립트 딥 다이브 12장 읽기

**Comment by Largopie** [comment]
어제 간 '마호가니 (종로쪽임)' 카페를 갔는데 확실히 커피도 맛이 괜찮았고 점심에는 직장인들로 붐벼 싞끌빡작했지만 확실히 공부하기에는 좋은 환경이였던 것 같다. 개인적인 평가로 4점(1점은 점심시간 씪끌빢짞 뺌) 언제든 가서 공부하기는 좋은 카페임이 분명하다. 내일도 열심히~!
