### ISSUE TITLE
2024.01.12 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#82]
- [x] 모던 자바스크립트 딥다이브 12장 읽기
- [x] 코딩테스트 3문제 풀기
- [x] 인터렉티브 웹 강의 수강

**Comment by Largopie** [comment]
오늘은 강남의 카페 '에이비카페'로 갔다. 신논현역과 강남 사이에 있는 카페였는데 24시간 카페인데도 굉장히 깔끔하고 공부하기 좋은 조용한 환경인게 굉장히 좋았다. 유느님이 3번 왔다 간 카페라고 한다. 다만, 아메리카노의 비용이 6500원이라는 기하학적인 숫자가 나와 조금 당황스러운 부분은 있었다. 이 카페를 별점으로 표현하자면 음... 아마도 ⭐️⭐️⭐️⭐️/5 쯤..? 될 것 같다. 역시 강남의 물가는 비싼 것 같다.
