### ISSUE TITLE
2024.01.15 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#85]
- [x] 코딩테스트 1문제 풀기
- [x] 리액트 면접 스터디 질문 답변 1개 작성하기
- [x] 인터렉티브 웹 강의 수강

**Comment by Largopie** [comment]
어제는 머니 이슈로 인해 주에 2번으로 원정 공부를 줄이고 다시 원래 다니던 몰빵카페로 행했다. 근데 공부 습관을 조금씩 들여가고 있어서였는지 전에 비해서는 공부 효율이 좋았다고 생각한다. 내일도 열심히 달려가보자!
