### ISSUE TITLE
2024.01.16 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#86]
- [x] 코딩테스트 2문제 풀기
- [x] 리액트 면접 스터디 질문 1개 답변하기
- [x] 인터렉티브 웹 강의 수강

**Comment by Largopie** [comment]
어제는 기존에 사다리타기에서 걸렸던 연희동에 위치한 '프로토콜'로 가기로 했으나 홍대입구에 도착하는 시점에서 국밥이 먹고 싶은 나머지 카페 주변의 국밥집을 검색해봤는데 모두 11,000원의 어마무시한 가격이 기다리고 있었다. 그래도 국밥 비스무리한 것을 먹고싶은 나머지 계획을 급 선회하여 연남동에 위치한 송가네 감자탕 본점으로 향했다. 해당 가게에서 뼈해장국을 시켜먹었는데 워.. 존맛탱이였다. 아무튼 그렇게 뼈해장국을 먹고 뜬금 없이 근처에 위치한 카페 공명으로 향해 공부를 했다. 근데 의외로 공부 환경이 굉장히 좋아 만족스럽게 공부를 마쳤다. 끗
