### ISSUE TITLE
2024.01.17 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#87]
- [x] 개발 관련 영상 2개 시청하기
- [x] 코딩테스트 2문제 이상 풀기
- [x] 모던 자바스크립트 딥다이브 13장 읽기
- [x] 기술 면접 스터디 리액트 질문 1개 답하기
- [ ] 시간 남으면 인터렉티브 웹 강의 수강

**Comment by Largopie** [comment]
어제 꽤 많은 것을 해냈다. 이제 돈이 줄줄 새는 이슈로 원정 카페 공부는 주 1회로 제한하고 다시 몰빵으로 복귀했다. 근데 한번 집중이 잘 되어서 그런가 다시 집중력이 증가했다. 그리고 너무 일찍 가기보다는 조금 적당한 시간에 빡 집중하는 방식으로 진행해서 짧은 시간에도 많은 효율을 낼 수 있는 것 같다. 화이팅~!
