### ISSUE TITLE
2024.01.18 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#88]
- [x] 코딩테스트 2문제 이상 풀기
- [x] 모던 자바스크립트 딥다이브 14강 읽고 정리
- [x] 면접 스터디 리액트 질문 1개 답변하기

**Comment by Largopie** [comment]
이제야 후기를 쓰게 되었지만 뭐.. 무난한 하루였던 것 같다.
