### ISSUE TITLE
2023.10.29 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#9]
- [x] getDerivedStateFromProps가 왜 static 메서드인지 고민해보기
- [x] 우아한테크코스 1주차 공통 피드백 수용해서 자동차 경주 리팩토링 하기
- [ ] 취업과 창업 시험 준비(대학 시험)
- [ ] 면접 스터디 모의 면접 준비
- [ ] 시간 남으면 클래스 컴포넌트 형태의 리액트 익히기
[ReactJS로 영화 웹서비스 만들기](https://nomadcoders.co/react-for-beginners/lobby?utm_source=free_course&utm_campaign=react-for-beginners&utm_medium=site)

**Comment by Largopie** [comment]
오늘은 우아한테크코스 1주차에 올라온 코드들을 보며 코드 리뷰를 진행했다. 나도 잘 아는 입장은 아니지만 더 나은 코드에 대해서 고민하며 리뷰를 작성했던 것 같다. 

그리고 어떨결에 블로그 글을 2개나 쓰게 됐다. `getDerivedStateFromProps가` 왜 `static메서드`인지 궁금증이 생겨 해당 자료를 찾아봤는데 블로그에 올라온 글은 못 본 것 같았다. 그래서 직접 자료를 찾으며 이해한 내용을 바탕으로 블로그 글을 작성해봤다.
[왜 getDerivedStateFromProps는 static메서드일까?-velog](https://velog.io/@largopie/React-%EC%99%9C-getDerivedStateFromProps%EB%8A%94-static-%EB%A9%94%EC%84%9C%EB%93%9C%EC%9D%BC%EA%B9%8C)

또 우아한테크코스 1주차 공통 피드백을 보고 `eslint`, prettier를 적용해보려 시도했다. npm으로 설치해야하는 부분이 있어서 `package.json`의 변경 불가피했지만, '해당 파일의 변경사항이 없어야 한다' 라는 요구사항이 있어 올라가지 않는 방법을 요리 조리 찾아봤다.
찾아본 결과에 대한 글은 여기있다.
[특정 파일 임시적으로 커밋 제외 시키기](https://velog.io/@largopie/git-%ED%8A%B9%EC%A0%95-%ED%8C%8C%EC%9D%BC-%EC%9E%84%EC%8B%9C%EC%A0%81%EC%9C%BC%EB%A1%9C-%EC%BB%A4%EB%B0%8B%EC%97%90-%EC%A0%9C%EC%99%B8%ED%95%98%EA%B8%B0)

이 두 글을 쓰다 보니 시간이 어느새 훌쩍 지나 있었고, 1시가 넘은 지금부터 시험 공부를 또 준비해봐야겠다..!

내일은 시험이 끝나면 졸업작품 프로젝트, 자동차 경주 미션 commit 넣기 정도 하면 적당할 것 같다!
내일도 화이팅! 👊
