### ISSUE TITLE
2024.01.21 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#91]
- [x] 모던 자바스크립트 딥 다이브 스터디
- [x] 모의 면접 스터디 리액트 질문 1개 답하기
- [x] 코딩테스트 1문제 풀기

**Comment by Largopie** [comment]
어제는 스터디에 참여는 했지만 사정이 생겨 다음주로 미뤄지게 되었다. 그래서 다음주에 13~16까지 공부해오기로했다!
