### ISSUE TITLE
2024.01.24 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#94]
- [x] 우아한테크코스 관련 글 몇 가지 읽어보기
- [x] 면접 스터디 질문 답변 3가지 작성
- [x] 모던 자바스크립트 딥 다이브 15장 읽기

**Comment by Largopie** [comment]
2일간의 쿠팡의 영향력인지 집중을 하는데 어려움이 조금은 있지만 언제나 그랬듯이 나는 적응해 갈 것이다.
