### ISSUE TITLE
2024.01.25 TODO

### ISSUE THREAD

**Issue by Largopie** [Largopie/TIL#95]
- [x] 우아한테크코스 정보, 후기 찾아보기
- [x] 코딩테스트 1문제 이상 풀기
- [x] 모던 자바스크립트 딥다이브 16장 읽기
- [x] 모의 면접 스터디 질문 답변하기
- [x] 인터렉티브 웹 강의 수강하기

**Comment by Largopie** [comment]
이제 다음주부터는 이사 준비로 조금 바빠질 예정이다. 조금조금씩 해나가자!
